// Terraform skeleton generator
export function generateTerraform(winner, workload) {
  if (!winner) return "# No winner selected"

  const { vendor, compute_service, storage_service } = winner
  const region = workload.region || "us-east-1"

  let tf = `# Generated by CASE Optimizer
# Cloud Architecture: ${vendor} ${compute_service} + ${storage_service}
# Region: ${region}
# Estimated Cost: $${winner.monthly_cost.toFixed(2)}/month
# Performance: ${winner.p95_ms.toFixed(1)}ms p95

terraform {
  required_providers {
`

  // Add provider based on vendor
  if (vendor === "aws") {
    tf += `    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
`
  } else if (vendor === "azure") {
    tf += `    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
`
  } else if (vendor === "gcp") {
    tf += `    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
`
  }

  tf += `  }
}

`

  // Provider configuration
  if (vendor === "aws") {
    tf += `provider "aws" {
  region = "${region}"
}

`

    // Compute resource
    if (compute_service === "lambda") {
      tf += `# Lambda Function
resource "aws_lambda_function" "main" {
  function_name = "case-optimizer-function"
  runtime       = "nodejs20.x"  # Adjust as needed
  handler       = "index.handler"
  role          = aws_iam_role.lambda_role.arn
  memory_size   = ${Math.ceil(workload.mem_gb * 1024)}
  timeout       = ${Math.ceil(workload.avg_exec_ms / 1000)}

  # Add your code deployment here
  filename = "lambda.zip"
}

resource "aws_iam_role" "lambda_role" {
  name = "case-optimizer-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}
`
    } else if (compute_service === "fargate") {
      tf += `# ECS Fargate Cluster
resource "aws_ecs_cluster" "main" {
  name = "case-optimizer-cluster"
}

resource "aws_ecs_task_definition" "main" {
  family                   = "case-optimizer-task"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "${Math.ceil(workload.cpu_vcpu * 1024)}"
  memory                   = "${Math.ceil(workload.mem_gb * 1024)}"

  container_definitions = jsonencode([{
    name  = "app"
    image = "your-image:latest"  # Replace with your image
    portMappings = [{
      containerPort = 80
      protocol      = "tcp"
    }]
  }])
}
`
    } else if (compute_service === "eks") {
      tf += `# EKS Cluster
resource "aws_eks_cluster" "main" {
  name     = "case-optimizer-cluster"
  role_arn = aws_iam_role.eks_role.arn

  vpc_config {
    subnet_ids = []  # Add your subnet IDs
  }
}

resource "aws_iam_role" "eks_role" {
  name = "case-optimizer-eks-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "eks.amazonaws.com"
      }
    }]
  })
}
`
    } else if (compute_service === "ec2") {
      tf += `# EC2 Instance
resource "aws_instance" "main" {
  ami           = "ami-xxxxx"  # Replace with appropriate AMI
  instance_type = "t3.${workload.mem_gb >= 2 ? "medium" : "small"}"

  tags = {
    Name = "case-optimizer-instance"
  }
}
`
    }

    // Storage resource
    if (storage_service === "s3") {
      tf += `
# S3 Bucket
resource "aws_s3_bucket" "main" {
  bucket = "case-optimizer-bucket-\${random_id.bucket_id.hex}"
}

resource "random_id" "bucket_id" {
  byte_length = 8
}
`
    } else if (storage_service === "dynamodb") {
      tf += `
# DynamoDB Table
resource "aws_dynamodb_table" "main" {
  name         = "case-optimizer-table"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "id"

  attribute {
    name = "id"
    type = "S"
  }
}
`
    } else if (storage_service === "rds-aurora") {
      tf += `
# RDS Aurora Cluster
resource "aws_rds_cluster" "main" {
  cluster_identifier = "case-optimizer-cluster"
  engine             = "aurora-postgresql"
  engine_version     = "15.3"
  database_name      = "casedb"
  master_username    = "admin"
  master_password    = "changeme123"  # Use secrets manager in production
  skip_final_snapshot = true
}
`
    }
  } else if (vendor === "azure") {
    tf += `provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = "case-optimizer-rg"
  location = "${region.replace('us-', '').replace('east', 'East US').replace('west', 'West US')}"
}

`

    if (compute_service === "functions") {
      tf += `# Azure Function App
resource "azurerm_storage_account" "main" {
  name                     = "caseoptimizerstorage"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "main" {
  name                = "case-optimizer-plan"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  kind                = "FunctionApp"
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "main" {
  name                       = "case-optimizer-func"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  app_service_plan_id        = azurerm_app_service_plan.main.id
  storage_account_name       = azurerm_storage_account.main.name
  storage_account_access_key = azurerm_storage_account.main.primary_access_key
}
`
    } else if (compute_service === "container-apps") {
      tf += `# Azure Container Apps
resource "azurerm_container_app_environment" "main" {
  name                = "case-optimizer-env"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_container_app" "main" {
  name                         = "case-optimizer-app"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {
    container {
      name   = "app"
      image  = "your-image:latest"
      cpu    = ${workload.cpu_vcpu}
      memory = "${workload.mem_gb}Gi"
    }
  }
}
`
    }

    if (storage_service === "blob") {
      tf += `
# Azure Blob Storage
resource "azurerm_storage_account" "storage" {
  name                     = "caseoptimizerstorage"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "main" {
  name                  = "data"
  storage_account_name  = azurerm_storage_account.storage.name
  container_access_type = "private"
}
`
    }
  } else if (vendor === "gcp") {
    tf += `provider "google" {
  project = "your-project-id"  # Replace with your GCP project ID
  region  = "${region}"
}

`

    if (compute_service === "cloud-functions") {
      tf += `# Cloud Function
resource "google_cloudfunctions_function" "main" {
  name        = "case-optimizer-function"
  runtime     = "nodejs20"
  entry_point = "handler"

  available_memory_mb = ${Math.ceil(workload.mem_gb * 1024)}
  timeout             = ${Math.ceil(workload.avg_exec_ms / 1000)}

  source_archive_bucket = google_storage_bucket.function_bucket.name
  source_archive_object = google_storage_bucket_object.function_archive.name

  trigger_http = true
}

resource "google_storage_bucket" "function_bucket" {
  name     = "case-optimizer-function-bucket"
  location = "US"
}

resource "google_storage_bucket_object" "function_archive" {
  name   = "function-source.zip"
  bucket = google_storage_bucket.function_bucket.name
  source = "function-source.zip"  # Replace with your source
}
`
    } else if (compute_service === "cloud-run") {
      tf += `# Cloud Run Service
resource "google_cloud_run_service" "main" {
  name     = "case-optimizer-service"
  location = "${region}"

  template {
    spec {
      containers {
        image = "gcr.io/your-project/your-image:latest"  # Replace
        resources {
          limits = {
            cpu    = "${workload.cpu_vcpu}"
            memory = "${Math.ceil(workload.mem_gb)}Gi"
          }
        }
      }
    }
  }
}
`
    } else if (compute_service === "gke") {
      tf += `# GKE Cluster
resource "google_container_cluster" "main" {
  name     = "case-optimizer-cluster"
  location = "${region}"

  initial_node_count = 2

  node_config {
    machine_type = "n1-standard-${workload.mem_gb >= 4 ? 2 : 1}"
  }
}
`
    }

    if (storage_service === "gcs") {
      tf += `
# Google Cloud Storage Bucket
resource "google_storage_bucket" "main" {
  name     = "case-optimizer-bucket-\${random_id.bucket_id.hex}"
  location = "US"
}

resource "random_id" "bucket_id" {
  byte_length = 8
}
`
    }
  }

  tf += `
# Outputs
output "architecture_summary" {
  value = {
    vendor  = "${vendor}"
    compute = "${compute_service}"
    storage = "${storage_service}"
    region  = "${region}"
  }
}
`

  return tf
}
